Check if backup directory exists

diff --git a/hooks/post-commit b/hooks/post-commit
--- a/hooks/post-commit
+++ b/hooks/post-commit
@@ -15,5 +15,17 @@ BACKUP_FILE=$REPO_NAME-$(date '+%Y%m%d%H%M%S')
 BACKUP_FULL_PATH=$GIT_LOCAL_BACKUP_DIR/$BACKUP_FILE
 BACKUP_SUCCESSFUL_MESSAGE=$(printf 'backup created: %s' "$BACKUP_FULL_PATH")
 
-git bundle create "$BACKUP_FULL_PATH" --all
+# exit if backup directory doesn't exist
+if [ ! -d "$GIT_LOCAL_BACKUP_DIR" ]; then
+    echo $HEADER
+    printf "git-local-backup error: %s directory doesn't exist\n" "$GIT_LOCAL_BACKUP_DIR"
+    echo $HEADER
+    echo
+    exit 1
+fi
+
+if ! git bundle create "$BACKUP_FULL_PATH" --all; then
+    exit 1
+fi
+
 printf '\n%s\n%s\n%s\n\n' "$HEADER" "$BACKUP_SUCCESSFUL_MESSAGE" "$HEADER"
